### ISSUE TITLE
Gestion du manque d’information pour un attribut

### ISSUE THREAD

**Issue by GT-CNIG-DDU** [cnigfr/schema-paysage#42]
Le standard Paysage pourrait proposer des valeurs conventionnelles pour gérer le défaut de renseignement d'un attribut à remplissage obligatoire. Par exemple : 

- inconnu (signifiant : "inconnu, non renseigné, ou information non disponible")
- autre
- sans objet

**Comment by DominiqueLaurent** [comment]
Dans le cadre d'une mise en oeuvre réelle du standard, il est attendu que tous les attributs obligatoires soient remplis.  Le cas qui avait posé problème lors des tests (atlas non publié en ligne) ne serait pas acceptable en conditions réelles : les données SIG doivent être complétées par la possibilité d'accéder à l'atlas, elles doivent être une porte d'entrée vers l'atlas.
